package com.tvodnica.gamesinfo.api.apimodels

import com.google.gson.annotations.SerializedName


data class GameApi(

    @SerializedName("id") var id: Int? = null,
    @SerializedName("slug") var slug: String? = null,
    @SerializedName("name") var name: String? = null,
    @SerializedName("name_original") var nameOriginal: String? = null,
    @SerializedName("description") var description: String? = null,
    @SerializedName("metacritic") var metacritic: Int? = null,
    @SerializedName("metacritic_platforms") var metacriticPlatformApis: ArrayList<MetacriticPlatformsApi> = arrayListOf(),
    @SerializedName("released") var released: String? = null,
    @SerializedName("tba") var tba: Boolean? = null,
    @SerializedName("updated") var updated: String? = null,
    @SerializedName("background_image") var backgroundImage: String? = null,
    @SerializedName("background_image_additional") var backgroundImageAdditional: String? = null,
    @SerializedName("website") var website: String? = null,
    @SerializedName("rating") var rating: Double? = null,
    @SerializedName("rating_top") var ratingTop: Int? = null,
    @SerializedName("ratings") var ratings: ArrayList<RatingsApi> = arrayListOf(),
    @SerializedName("reactions") var reactionsApi: ReactionsApi? = ReactionsApi(),
    @SerializedName("added") var added: Int? = null,
    @SerializedName("added_by_status") var addedByStatus: AddedByStatusApi? = AddedByStatusApi(),
    @SerializedName("playtime") var playtime: Int? = null,
    @SerializedName("screenshots_count") var screenshotsCount: Int? = null,
    @SerializedName("movies_count") var moviesCount: Int? = null,
    @SerializedName("creators_count") var creatorsCount: Int? = null,
    @SerializedName("achievements_count") var achievementsCount: Int? = null,
    @SerializedName("parent_achievements_count") var parentAchievementsCount: Int? = null,
    @SerializedName("reddit_url") var redditUrl: String? = null,
    @SerializedName("reddit_name") var redditName: String? = null,
    @SerializedName("reddit_description") var redditDescription: String? = null,
    @SerializedName("reddit_logo") var redditLogo: String? = null,
    @SerializedName("reddit_count") var redditCount: Int? = null,
    @SerializedName("twitch_count") var twitchCount: Int? = null,
    @SerializedName("youtube_count") var youtubeCount: Int? = null,
    @SerializedName("reviews_text_count") var reviewsTextCount: Int? = null,
    @SerializedName("ratings_count") var ratingsCount: Int? = null,
    @SerializedName("suggestions_count") var suggestionsCount: Int? = null,
    @SerializedName("alternative_names") var alternativeNames: ArrayList<String> = arrayListOf(),
    @SerializedName("metacritic_url") var metacriticUrl: String? = null,
    @SerializedName("parents_count") var parentsCount: Int? = null,
    @SerializedName("additions_count") var additionsCount: Int? = null,
    @SerializedName("game_series_count") var gameSeriesCount: Int? = null,
    @SerializedName("user_game") var userGame: String? = null,
    @SerializedName("reviews_count") var reviewsCount: Int? = null,
    @SerializedName("saturated_color") var saturatedColor: String? = null,
    @SerializedName("dominant_color") var dominantColor: String? = null,
    @SerializedName("parent_platforms") var parentPlatformApis: ArrayList<ParentPlatformsApi> = arrayListOf(),
    @SerializedName("platforms") var platforms: ArrayList<PlatformsApi> = arrayListOf(),
    @SerializedName("stores") var stores: ArrayList<StoresApi> = arrayListOf(),
    @SerializedName("developers") var developers: ArrayList<DevelopersApi> = arrayListOf(),
    @SerializedName("genres") var genres: ArrayList<GenresApi> = arrayListOf(),
    @SerializedName("tags") var tags: ArrayList<TagsApi> = arrayListOf(),
    @SerializedName("publishers") var publishers: ArrayList<PublishersApi> = arrayListOf(),
    @SerializedName("esrb_rating") var esrbRatingApi: EsrbRatingApi? = EsrbRatingApi(),
    @SerializedName("clip") var clip: String? = null,
    @SerializedName("description_raw") var descriptionRaw: String? = null

)